version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
      lint-and-format:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'typescript-eslint'
          - 'prettier*'
      test-tooling:
        patterns:
          - 'vitest'
          - '@vitest/*'
          - 'jsdom'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
